name             'lootcrate-cookbook'
maintainer       'Jason Carter'
maintainer_email 'jason.carter@lootcrate.com'
license          'All rights reserved'
description      'Installs/Configures cookbook'
long_description 'Installs/Configures cookbook'
version          '0.1.0'
